spring.application.name=ms-usuarios
server.port=8081

# Conexión a BD
spring.datasource.url=jdbc:mysql://localhost:3306/db_usuarios?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=1234

# Generación de tablas
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# monitoreo de salud
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always